#!/usr/bin/env sh
solana_keygen=./target/release/solana-keygen
SOLANA_CONFIG_DIR=./config

mkdir $SOLANA_CONFIG_DIR
$solana_keygen new --no-passphrase -so "$SOLANA_CONFIG_DIR"/a/identity.json
$solana_keygen new --no-passphrase -so "$SOLANA_CONFIG_DIR"/a/stake-account.json
$solana_keygen new --no-passphrase -so "$SOLANA_CONFIG_DIR"/a/vote-account.json

$solana_keygen new --no-passphrase -so "$SOLANA_CONFIG_DIR"/b/identity.json
$solana_keygen new --no-passphrase -so "$SOLANA_CONFIG_DIR"/b/stake-account.json
$solana_keygen new --no-passphrase -so "$SOLANA_CONFIG_DIR"/b/vote-account.json

NDEBUG=1 ./multinode-demo/setup.sh
./target/release/solana-ledger-tool -l config/bootstrap-validator/ create-snapshot 0
NDEBUG=1 ./multinode-demo/faucet.sh
