[package]
name = "jito-protos"
version = "1.17.0"
edition = "2021"
publish = false

[dependencies]
bytes = {workspace = true}
prost = {workspace = true}
prost-types = {workspace = true}
tonic = {workspace = true}

[build-dependencies]
tonic-build = {workspace = true}
